import sqlite3
CACHE = r"D:/codex-A股交易/trading_local.sqlite3"
MH    = r"D:/codex-A股交易/market_history.sqlite3"
c = sqlite3.connect(f"file:{CACHE}?mode=ro", uri=True)
m = sqlite3.connect(f"file:{MH}?mode=ro", uri=True)
print("== cache daily_bar_cache schema ==")
for r in c.execute("SELECT sql FROM sqlite_master WHERE name='daily_bar_cache'"): print(r[0])
print("\n== sample symbols ==")
for r in c.execute("SELECT symbol, trade_date, close, source, adjustment_mode, volume_unit FROM daily_bar_cache LIMIT 5"): print(r)
print("\n== distinct symbol prefixes (2 chars) in cache ==")
for r in c.execute("SELECT substr(symbol,1,2), COUNT(DISTINCT symbol), COUNT(*) FROM daily_bar_cache GROUP BY 1 ORDER BY 3 DESC LIMIT 20"): print(r)
print("\n== symbol length distribution ==")
for r in c.execute("SELECT length(symbol), COUNT(DISTINCT symbol) FROM daily_bar_cache GROUP BY 1"): print(r)
print("\n== cache adjustment_mode / source distribution ==")
for r in c.execute("SELECT adjustment_mode, source, COUNT(*) FROM daily_bar_cache GROUP BY 1,2 ORDER BY 3 DESC LIMIT 20"): print(r)
print("\n== mh daily_bars schema ==")
for r in m.execute("SELECT sql FROM sqlite_master WHERE name='daily_bars'"): print(r[0])
print("\n== mh adjustment_mode distribution ==")
for r in m.execute("SELECT adjustment_mode, COUNT(*), COUNT(DISTINCT symbol) FROM daily_bars GROUP BY 1"): print(r)
print("\n== mh sample symbols ==")
for r in m.execute("SELECT symbol, trade_date, close, adjustment_mode, provider FROM daily_bars LIMIT 5"): print(r)
print("\n== mh instruments schema ==")
for r in m.execute("SELECT sql FROM sqlite_master WHERE name='instruments'"): print(r[0])
print("\n== mh instruments sample ==")
for r in m.execute("SELECT symbol, name, list_date, delist_date, status, exchange, asset_type, board FROM instruments LIMIT 8"): print(r)
print("\n== mh instruments exchange x asset_type ==")
for r in m.execute("SELECT exchange, asset_type, board, COUNT(*) FROM instruments GROUP BY 1,2,3 ORDER BY 4 DESC LIMIT 30"): print(r)
