import sqlite3
MH=r"D:/codex-A股交易/market_history.sqlite3"
TL=r"D:/codex-A股交易/trading_local.sqlite3"
c=sqlite3.connect(f"file:{MH}?mode=ro",uri=True)
print(c.execute("SELECT sql FROM sqlite_master WHERE name='daily_bars'").fetchone()[0])
print("--- indexes on daily_bars")
for r in c.execute("SELECT name,sql FROM sqlite_master WHERE type='index' AND tbl_name='daily_bars'"): print(r)
print("--- adjustment_mode dist (market_history.daily_bars)")
for r in c.execute("SELECT adjustment_mode,COUNT(*),COUNT(DISTINCT symbol),MIN(trade_date),MAX(trade_date) FROM daily_bars GROUP BY 1"): print(r)
print("--- volume_unit dist")
for r in c.execute("SELECT volume_unit,COUNT(*) FROM daily_bars GROUP BY 1"): print(r)
print("--- provider dist")
for r in c.execute("SELECT provider,COUNT(*),COUNT(DISTINCT symbol) FROM daily_bars GROUP BY 1"): print(r)
print("--- schema_metadata")
for r in c.execute("SELECT * FROM schema_metadata"): print(r)
c.close()
t=sqlite3.connect(f"file:{TL}?mode=ro",uri=True)
print("="*60)
print(t.execute("SELECT sql FROM sqlite_master WHERE name='daily_bar_cache'").fetchone()[0])
print("--- cache adjustment_mode dist")
for r in t.execute("SELECT adjustment_mode,COUNT(*),COUNT(DISTINCT symbol),MIN(trade_date),MAX(trade_date) FROM daily_bar_cache GROUP BY 1"): print(r)
print("--- cache source dist")
for r in t.execute("SELECT source,COUNT(*),COUNT(DISTINCT symbol) FROM daily_bar_cache GROUP BY 1 ORDER BY 2 DESC"): print(r)
print("--- cache created_at day dist (top 15)")
for r in t.execute("SELECT substr(created_at,1,10),COUNT(*) FROM daily_bar_cache GROUP BY 1 ORDER BY 2 DESC LIMIT 15"): print(r)
print("--- cache updated_at day dist (top 15)")
for r in t.execute("SELECT substr(updated_at,1,10),COUNT(*) FROM daily_bar_cache GROUP BY 1 ORDER BY 2 DESC LIMIT 15"): print(r)
t.close()
