"""Freeze cutoff-only inputs for actual independent M3-03 agent reviews.

No SQLite or network. Copies already source-validated cores, retaining every
core/prefix binding. No verdicts or review entries are generated by this script.
"""
import copy
from datetime import datetime, timezone
import gzip
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[3]
HERE=Path(__file__).resolve().parent
RUN=ROOT/'claude methods/_m3_20260910/claude_02/runs/dev_run_02'
MANIFEST=RUN.parents[1]/'artifact_manifest.json'
SOURCE_REVIEW=HERE/'reader_chronology_source_review_02/result.json'
PACKET_REVIEW=HERE/'reader_episode_packet_review_03/result.json'
PINS={MANIFEST:'4aa337d9840c970700bad7f2566af7e7a84a486ec8180c1b0295664bc0662962',
      SOURCE_REVIEW:'a0a0e3013ba3f796385fd2a886d4ce4bf0e737edf376b3072ad015ccda7ca4a1',
      PACKET_REVIEW:'b8d445a913bc5dac6386ad73696fc0084d84b7383e3005f22c5637c6edfbbde9'}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    output=HERE/'case_review_bundle_01'
    assert not output.exists()
    for path,pin in PINS.items():
        assert sha(path)==pin
    manifest=json.loads(MANIFEST.read_text(encoding='utf-8'))
    audit=json.loads(PACKET_REVIEW.read_text(encoding='utf-8'))
    assert audit['passed'] and audit['packet_reasons']['matched_pending']==32
    all_records={}; by_hash={}; origins={}
    index=json.loads((RUN/'chronology_index.json').read_text(encoding='utf-8'))
    for symbol,item in index['files'].items():
        path=RUN/'chronology'/(symbol+'.jsonl.gz')
        assert sha(path)==item['sha256_gzip']
        rows=[json.loads(line)['record'] for line in gzip.decompress(path.read_bytes()).decode('utf-8').splitlines()]
        all_records[symbol]=rows
        for line,record in enumerate(rows):
            assert not record['review_ledger']['entries']
            by_hash[record['record_hash']]=record
            origins[record['record_hash']]={'chronology_file':str(path.relative_to(ROOT)),'file_sha256':item['sha256_gzip'],'line':line}
    # Selection is the entire pre-existing matched inventory, not a new outcome screen.
    selected=sorted((x for x in audit['checks'] if x['exclusion'] is None),key=lambda x:(x['representative_date'],by_hash[json.loads((RUN/'packets'/(x['episode_key']+'.json')).read_text(encoding='utf-8'))['representative']['record_hash']]['symbol']))
    assert len(selected)==32
    output.mkdir();(output/'cases').mkdir();(output/'diagnostics').mkdir()
    written={};case_index=[]

    def write(name,value):
        path=output/name
        path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
        written[name]={'sha256':sha(path),'bytes':path.stat().st_size}
        return written[name]['sha256']

    for number,item in enumerate(selected,1):
        case_id=f'C{number:03d}'
        packet_path=RUN/'packets'/(item['episode_key']+'.json')
        assert sha(packet_path)==item['packet_sha256']
        packet=json.loads(packet_path.read_text(encoding='utf-8'))
        rep=by_hash[packet['representative']['record_hash']]
        prefix=[by_hash[x['record_hash']] for x in packet['members']]
        controls=[by_hash[x['record_hash']] for x in packet['controls']]
        assert len(prefix)==3 and 3<=len(controls)<=5
        assert all(x['cutoff']['decision_date']<=rep['cutoff']['decision_date'] for x in prefix+controls)
        view=copy.deepcopy(packet)
        for ref in [view['representative'],*view['members'],*view['controls']]:
            ref.pop('chronology_file',None);ref.pop('line',None)
        content={k:v for k,v in view.items() if k not in ('cutoff_packet_hash','review_status','reviews')}
        digest=hashlib.sha256(json.dumps(content,ensure_ascii=False,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()
        assert digest==view['cutoff_packet_hash']
        value={'schema':'m3.actual_review_input.v1','case_id':case_id,'purpose':'actual individual agent review; no verdict generated',
            'cutoff_packet':view,'prefix_records':prefix,'representative_record':rep,'control_records':controls,
            'source_binding':{'delivery_manifest_sha256':PINS[MANIFEST],'source_replay_sha256':PINS[SOURCE_REVIEW],
                'packet_audit_sha256':PINS[PACKET_REVIEW],'original_packet_sha256':item['packet_sha256'],
                'core_origins':{r['record_hash']:origins[r['record_hash']] for r in prefix+controls}},
            'review_status':'pending_actual_individual_reviews','reviews':[]}
        relative='cases/'+case_id+'.json';pin=write(relative,value)
        case_index.append({'case_id':case_id,'path':relative,'sha256':pin,'symbol':rep['symbol'],'decision_date':rep['cutoff']['decision_date'],
            'episode_id':rep['episode_id'],'record_hash':rep['record_hash'],'case_prefix_hash':packet['prefix_proof']['prefix_hash'],
            'cutoff_packet_hash':packet['cutoff_packet_hash'],'control_count':len(controls)})

    # Explicit diagnostic examples retain failure/ambiguity and entry/no-trade semantics.
    # Each is the earliest (date,symbol) record satisfying a stated contemporaneous rule.
    chronological=sorted(by_hash.values(),key=lambda r:(r['cutoff']['decision_date'],r['symbol']))
    predicates=[('markup_phase',lambda r:r['labels']['phase']['label']=='markup'),
        ('distribution_phase',lambda r:r['labels']['phase']['label']=='distribution'),
        ('failed_markup_phase',lambda r:r['labels']['phase']['label']=='failed_markup'),
        ('warmup_indeterminate',lambda r:r['labels']['phase']['label']=='indeterminate' and any('insufficient_warmup' in x for x in r['data_quality'])),
        ('suspended_decision',lambda r:r['current_state']=='suspended'),
        ('known_cash_action_gate',lambda r:'known_corporate_action_in_window' in r['data_quality']),
        ('entry_signal_eligible_unverified_execution',lambda r:r['labels']['entry']['label']=='signal_eligible'),
        ('bj_scoped_exception',lambda r:r['features'].get('scope_exception_on_bar') is True)]
    diagnostics=[]
    for number,(kind,predicate) in enumerate(predicates,1):
        record=next(r for r in chronological if predicate(r))
        diag_id=f'D{number:03d}'
        value={'schema':'m3.actual_diagnostic_review_input.v1','case_id':diag_id,'diagnostic_kind':kind,
            'selection_rule':'Earliest (decision_date,symbol) in the fixed development chronology satisfying '+kind+'; no later outcome criterion.',
            'counts_as_positive_episode':False,'record':record,'origin':origins[record['record_hash']],
            'source_replay_sha256':PINS[SOURCE_REVIEW],'review_status':'pending_actual_individual_reviews','reviews':[]}
        relative='diagnostics/'+diag_id+'.json';pin=write(relative,value)
        diagnostics.append({'case_id':diag_id,'kind':kind,'path':relative,'sha256':pin,'symbol':record['symbol'],
            'decision_date':record['cutoff']['decision_date'],'record_hash':record['record_hash']})
    README='''# M3-03 cutoff-only individual review inputs

This bundle contains all 32 matched potential episodes from the independently accepted M3-02 development inventory, their three prefix cores and all 127 selected control uses. They are pending individual review. No script-generated verdict is present.

Eight additional examples, selected by the explicit earliest-date rules in index.json, retain markup/distribution/failed/indeterminate/suspension/cash-action/entry/exception semantics. These single-record diagnostics never count as positive episodes. No actual position was declared in this chronology, so position_event=no_trade is not an observed stop/exit history or a fill proof; the corresponding rule-family implementation was validated separately in M3-01.

Read cases/*.json and diagnostics/*.json using the index pins. Each case embeds the exact full cores needed for review; do not follow chronology locators into full later sequences. Source-binding origin paths are provenance metadata, not additional review inputs. Later episode end/status, full retrospective selection paths and outcome data are absent. Historical capture/assembly timestamps in evidence remain honestly marked as 2026; this is retrospective research with strict_pit=false and training_eligible=false.

Judge each case and every selected control with specific supporting and contradicting evidence, uncertainty and limits. A positive verdict refers to the frozen observable label proxy, not hidden actor behavior, future profit or a trade recommendation. Preserve ambiguity and disagreement; do not adjust policy or select replacements to force a target. Claude and Codex each perform their own actual agent review and retain execution evidence; neither writes the other's verdicts.
'''
    (output/'README.md').write_text(README,encoding='utf-8');written['README.md']={'sha256':sha(output/'README.md'),'bytes':(output/'README.md').stat().st_size}
    (output/'source.py').write_bytes(Path(__file__).read_bytes());written['source.py']={'sha256':sha(output/'source.py'),'bytes':(output/'source.py').stat().st_size}
    write('index.json',{'schema':'m3.cutoff_review_bundle_index.v1','created_at_utc':datetime.now(timezone.utc).isoformat(),
        'cases':case_index,'diagnostics':diagnostics,'case_count':32,'control_uses':sum(c['control_count'] for c in case_index),
        'actual_reviews_generated':0,'positive_target_met':False,'review_only':True,'live_trading_enabled':False,
        'strict_pit':False,'training_eligible':False,'policy_hash':'d436ba1402f9d0b53e1008c2a2bd50678a457c3e050561a59ded30dbbd21c025'})
    manifest_out={'schema':'m3.cutoff_review_bundle_manifest.v1','written':written,'inputs':{str(p):v for p,v in PINS.items()},
        'case_count':32,'diagnostic_count':8,'actual_reviews_generated':0,'sqlite_connections':0,'producer_sha256':sha(Path(__file__))}
    (output/'manifest.json').write_text(json.dumps(manifest_out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    for p,pin in PINS.items():assert sha(p)==pin
    print(json.dumps({'bundle':str(output),'manifest_sha256':sha(output/'manifest.json'),'case_count':32,'diagnostic_count':8,
        'control_uses':sum(c['control_count'] for c in case_index),'index_sha256':written['index.json']['sha256']},ensure_ascii=False))


if __name__=='__main__':
    main()
